services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Vados\TaskExecutorBundle\Service\:
    resource: '../../Service/*'

  Vados\TaskExecutorBundle\Repository\:
    resource: '../../Repository/*'

  Vados\TaskExecutorBundle\Command\TaskExecuteCommand:
    tags:
      - { name: 'console.command' }