name: run-tests-and-checks
on:
  pull_request:
    branches: [master]
jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: php-actions/composer@v1
      - uses: chindit/actions-phpunit@master
