name: run-tests-and-checks
on:
  pull_request:
    branches: [master]
jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{runner.os}}-php-${{hashFiles('**/composer.lock')}}
          restore-keys: |
            ${{runner.os}}-php-
      - uses: php-actions/composer@v1
      - run: composer install --prefer-dist --no-progress --no--suggest
      - uses: chindit/actions-phpunit@master
