name: run-tests-and-checks
on:
  pull_request:
    branches: [master]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: php-actions/composer@v1
      - uses: chindit/actions-phpunit@master
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: chindit/actions-phpstan@master
        with:
          arguments: 'src/ tests/ --level=5'
